/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ApplicationApplicationSyncRequest {
    dryRun?: boolean;

    infos?: Array<models.V1alpha1Info>;

    manifests?: Array<string>;

    name?: string;

    prune?: boolean;

    resources?: Array<models.V1alpha1SyncOperationResource>;

    revision?: string;

    strategy?: models.V1alpha1SyncStrategy;

}
