/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ClusterSettings {
    appLabelKey?: string;

    configManagementPlugins?: Array<models.V1alpha1ConfigManagementPlugin>;

    dexConfig?: models.ClusterDexConfig;

    googleAnalytics?: models.ClusterGoogleAnalyticsConfig;

    help?: models.ClusterHelp;

    kustomizeOptions?: models.V1alpha1KustomizeOptions;

    kustomizeVersions?: Array<string>;

    oidcConfig?: models.ClusterOIDCConfig;

    plugins?: Array<models.ClusterPlugin>;

    resourceOverrides?: { [key: string]: models.V1alpha1ResourceOverride; };

    statusBadgeEnabled?: boolean;

    url?: string;

    userLoginsDisabled?: boolean;

}
