/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface RepositoryManifestResponse {
    manifests?: Array<string>;

    namespace?: string;

    revision?: string;

    server?: string;

    sourceType?: string;

    verifyResult?: string;

}
