/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * SessionCreateRequest is for logging in.
 */
export interface SessionSessionCreateRequest {
    password?: string;

    token?: string;

    username?: string;

}
