/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ApplicationWatchEvent contains information about application change.
 */
export interface V1alpha1ApplicationWatchEvent {
    application?: models.V1alpha1Application;

    type?: string;

}
