/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1ResourceResult {
    group?: string;

    hookPhase?: string;

    hookType?: string;

    kind?: string;

    message?: string;

    name?: string;

    namespace?: string;

    status?: string;

    syncPhase?: string;

    version?: string;

}
