/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1Cluster {
    config?: models.V1alpha1ClusterConfig;

    connectionState?: models.V1alpha1ConnectionState;

    info?: models.V1alpha1ClusterInfo;

    name?: string;

    /**
     * Holds list of namespaces which are accessible in that cluster. Cluster level resources would be ignored if namespace list if not empty.
     */
    namespaces?: Array<string>;

    refreshRequestedAt?: models.V1Time;

    server?: string;

    serverVersion?: string;

}
