/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1ApplicationSummary {
    /**
     * ExternalURLs holds all external URLs of application child resources.
     */
    externalURLs?: Array<string>;

    /**
     * Images holds all images of application child resources.
     */
    images?: Array<string>;

}
