/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * SyncOperation contains sync operation details.
 */
export interface V1alpha1SyncOperation {
    dryRun?: boolean;

    manifests?: Array<string>;

    prune?: boolean;

    resources?: Array<models.V1alpha1SyncOperationResource>;

    /**
     * Revision is the revision in which to sync the application to. If omitted, will use the revision specified in app spec.
     */
    revision?: string;

    source?: models.V1alpha1ApplicationSource;

    syncOptions?: Array<string>;

    syncStrategy?: models.V1alpha1SyncStrategy;

}
