/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1ResourceNode {
    createdAt?: models.V1Time;

    health?: models.V1alpha1HealthStatus;

    images?: Array<string>;

    info?: Array<models.V1alpha1InfoItem>;

    networkingInfo?: models.V1alpha1ResourceNetworkingInfo;

    parentRefs?: Array<models.V1alpha1ResourceRef>;

    resourceRef?: models.V1alpha1ResourceRef;

    resourceVersion?: string;

}
