/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1ClusterInfo {
    applicationsCount?: string;

    cacheInfo?: models.V1alpha1ClusterCacheInfo;

    connectionState?: models.V1alpha1ConnectionState;

    serverVersion?: string;

}
