/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1TLSClientConfig {
    caData?: string;

    certData?: string;

    /**
     * Server should be accessed without verifying the TLS certificate. For testing only.
     */
    insecure?: boolean;

    keyData?: string;

    /**
     * ServerName is passed to the server for SNI and is used in the client to check server certificates against. If ServerName is empty, the hostname used to contact the server is used.
     */
    serverName?: string;

}
