/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1ApplicationStatus {
    conditions?: Array<models.V1alpha1ApplicationCondition>;

    health?: models.V1alpha1HealthStatus;

    history?: Array<models.V1alpha1RevisionHistory>;

    observedAt?: models.V1Time;

    operationState?: models.V1alpha1OperationState;

    reconciledAt?: models.V1Time;

    resources?: Array<models.V1alpha1ResourceStatus>;

    sourceType?: string;

    summary?: models.V1alpha1ApplicationSummary;

    sync?: models.V1alpha1SyncStatus;

}
