/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1OperationInitiator {
    /**
     * Automated is set to true if operation was initiated automatically by the application controller.
     */
    automated?: boolean;

    /**
     * Name of a user who started operation.
     */
    username?: string;

}
