/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ApplicationSpec represents desired application state. Contains link to repository with application definition and additional parameters link definition revision.
 */
export interface V1alpha1ApplicationSpec {
    destination?: models.V1alpha1ApplicationDestination;

    ignoreDifferences?: Array<models.V1alpha1ResourceIgnoreDifferences>;

    info?: Array<models.V1alpha1Info>;

    /**
     * Project is a application project name. Empty name means that application belongs to 'default' project.
     */
    project?: string;

    /**
     * This limits this number of items kept in the apps revision history. This should only be changed in exceptional circumstances. Setting to zero will store no history. This will reduce storage used. Increasing will increase the space used to store the history, so we do not recommend increasing it. Default is 10.
     */
    revisionHistoryLimit?: string;

    source?: models.V1alpha1ApplicationSource;

    syncPolicy?: models.V1alpha1SyncPolicy;

}
