/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ClusterConfig is the configuration attributes. This structure is subset of the go-client rest.Config with annotations added for marshalling.
 */
export interface V1alpha1ClusterConfig {
    awsAuthConfig?: models.V1alpha1AWSAuthConfig;

    /**
     * Server requires Bearer authentication. This client will not attempt to use refresh tokens for an OAuth2 flow. TODO: demonstrate an OAuth2 compatible client.
     */
    bearerToken?: string;

    password?: string;

    tlsClientConfig?: models.V1alpha1TLSClientConfig;

    username?: string;

}
