/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * ApplicationSource contains information about github repository, path within repository and target application environment.
 */
export interface V1alpha1ApplicationSource {
    chart?: string;

    directory?: models.V1alpha1ApplicationSourceDirectory;

    helm?: models.V1alpha1ApplicationSourceHelm;

    ksonnet?: models.V1alpha1ApplicationSourceKsonnet;

    kustomize?: models.V1alpha1ApplicationSourceKustomize;

    path?: string;

    plugin?: models.V1alpha1ApplicationSourcePlugin;

    repoURL?: string;

    targetRevision?: string;

}
