/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1ApplicationTree {
    /**
     * Nodes contains list of nodes which either directly managed by the application and children of directly managed nodes.
     */
    nodes?: Array<models.V1alpha1ResourceNode>;

    /**
     * OrphanedNodes contains if or orphaned nodes: nodes which are not managed by the app but in the same namespace. List is populated only if orphaned resources enabled in app project.
     */
    orphanedNodes?: Array<models.V1alpha1ResourceNode>;

}
