/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V1alpha1Repository {
    connectionState?: models.V1alpha1ConnectionState;

    enableLfs?: boolean;

    inheritedCreds?: boolean;

    insecure?: boolean;

    insecureIgnoreHostKey?: boolean;

    name?: string;

    password?: string;

    repo?: string;

    sshPrivateKey?: string;

    tlsClientCertData?: string;

    tlsClientCertKey?: string;

    type?: string;

    username?: string;

}
