/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Event is a report of an event somewhere in the cluster.
 */
export interface V1Event {
    action?: string;

    count?: number;

    eventTime?: models.V1MicroTime;

    firstTimestamp?: models.V1Time;

    involvedObject?: models.V1ObjectReference;

    lastTimestamp?: models.V1Time;

    message?: string;

    metadata?: models.V1ObjectMeta;

    reason?: string;

    related?: models.V1ObjectReference;

    reportingComponent?: string;

    reportingInstance?: string;

    series?: models.V1EventSeries;

    source?: models.V1EventSource;

    type?: string;

}
