/**
 * Consolidate Services
 * Description of all APIs
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * OwnerReference contains enough information to let you identify an owning object. An owning object must be in the same namespace as the dependent, or be cluster-scoped, so there is no namespace field.
 */
export interface V1OwnerReference {
    /**
     * API version of the referent.
     */
    apiVersion?: string;

    blockOwnerDeletion?: boolean;

    controller?: boolean;

    kind?: string;

    name?: string;

    uid?: string;

}
